export default (sequelize, DataTypes) => {
  const Footballer = sequelize.define('Footballer', {
      Name: { type: DataTypes.STRING, primaryKey: true },
      Nationality: DataTypes.STRING,
      National_Position: DataTypes.STRING,
      National_Kit: DataTypes.STRING,
      Club: DataTypes.STRING,
      Club_Position: DataTypes.STRING,
      Club_Kit: DataTypes.STRING,
      Club_Joining: DataTypes.STRING,
      Contract_Expiry: DataTypes.STRING,
      Height: DataTypes.STRING,
      Weight: DataTypes.STRING,
      Preffered_Foot: DataTypes.STRING,
      Birth_Date: DataTypes.STRING,
      Preffered_Position: DataTypes.STRING,
      Work_Rate: DataTypes.STRING,
      Rating: DataTypes.INTEGER,
      Age: DataTypes.INTEGER,
      Weak_foot: DataTypes.INTEGER,
      Skill_Moves: DataTypes.INTEGER,
      Ball_Control: DataTypes.INTEGER,
      Dribbling: DataTypes.INTEGER,
      Marking: DataTypes.INTEGER,
      Sliding_Tackle: DataTypes.INTEGER,
      Standing_Tackle: DataTypes.INTEGER,
      Aggression: DataTypes.INTEGER,
      Reactions: DataTypes.INTEGER,
      Attacking_Position: DataTypes.INTEGER,
      Interceptions: DataTypes.INTEGER,
      Vision: DataTypes.INTEGER,
      Composure: DataTypes.INTEGER,
      Crossing: DataTypes.INTEGER,
      Short_Pass: DataTypes.INTEGER,
      Long_Pass: DataTypes.INTEGER,
      Acceleration: DataTypes.INTEGER,
      Speed: DataTypes.INTEGER,
      Stamina: DataTypes.INTEGER,
      Strength: DataTypes.INTEGER,
      Balance: DataTypes.INTEGER,
      Agility: DataTypes.INTEGER,
      Jumping: DataTypes.INTEGER,
      Heading: DataTypes.INTEGER,
      Shot_Power: DataTypes.INTEGER,
      Finishing: DataTypes.INTEGER,
      Long_Shots: DataTypes.INTEGER,
      Curve: DataTypes.INTEGER,
      Freekick_Accuracy: DataTypes.INTEGER,
      Penalties: DataTypes.INTEGER,
      Volleys: DataTypes.INTEGER,
      GK_Positioning: DataTypes.INTEGER,
      GK_Diving: DataTypes.INTEGER,
      GK_Kicking: DataTypes.INTEGER,
      GK_Handling: DataTypes.INTEGER,
      GK_Reflexes: DataTypes.INTEGER
  }, {
    timestamps: false,
    freezeTableName: true,
    tableName: 'footballers',
  })

  return Footballer
}
